Numerous bug fixes for darcsit
Ignore-this: 24d2f9b98ae7db129c3969b61940e580

darcs-hash:139fd8be077adb4ab27b31e2e910d264aad84719

diff --git a/src/darcsit/cgi-bin/darcsit b/src/darcsit/cgi-bin/darcsit
--- a/src/darcsit/cgi-bin/darcsit
+++ b/src/darcsit/cgi-bin/darcsit
@@ -551,9 +551,7 @@ function status_warning()
 <div id=msg_logo><img src=/img/warning.png></div>
 <div id=msg_label>
 EOF
-	msg=$(sed -e "s|$DOCUMENT_ROOT\(/[^:]*\):\([0-9]*\):|<a href=\"\1#\2\">\1:\2</a>:|g"  \
-	          -e "s|^[~]*$1\.c:\([0-9]*\):|$1.c:<a href=\"#\1\">\1</a>:|g"   \
-		  -e 's/$/<br>/g' < "$1/warn")
+	msg=$(parse_errors "$1" < "$1/warn")
 	if [[ "$msg" ]]; then
 	    echo "$msg"
 	fi
@@ -561,6 +559,14 @@ cat <<EOF
 </div></div>
 EOF
     fi
+}
+
+function parse_errors()
+{
+    uniq | sed -e "s|$DOCUMENT_ROOT/\([^:]*\):\([0-9]*\):|<a href=\"/\1#\2\">\1:\2</a>:|g"  \
+	-e "s|^\./\([^:]*\):\([0-9]*\):|<a href=\"./\1#\2\">\1:\2</a>:|g"                   \
+	-e "s|^[~]*$1\.c:\([0-9]*\):|$1.c:<a href=\"$2#\1\">\1</a>:|g"                      \
+	-e 's/$/<br>/g'
 }
 
 function status_fail()
@@ -571,17 +577,16 @@ function status_fail()
 <div id=msg_logo><img src=/img/error.png></div>
 <div id=msg_label>
 EOF
+    local short=${1##\~}
+    msg=$(head -n 20 "$1/fail" | sed -r -e "s/$1/$short/g" | parse_errors "$short" "$2")
     if $BASILISK/darcsit/pagemagic < "$1.c"; then
-	msg=$(head -n 20 "$1/fail" | sed -e "/^$1\.c:*/d" -e 's/$/<br>/g')
 	if [[ ! "$msg" ]]; then
 	    head -n 20 "$1/fail" | sed 's/.*\(Program received signal.*\)/\1/;t;d'
 	else
 	    echo "$msg"
 	fi
     else
-	local short=${1##\~}
-	head -n 20 "$1/fail" | \
-	    sed -r -e "s/$1/$short/g" -e "s|^$short\.c:([0-9]+):*|<a href=\"$2#\1\">$short.c:\1:</a>|g" -e 's/$/<br>/g'
+	echo "$msg"
     fi
     cat <<EOF
 </div></div>
@@ -799,11 +804,20 @@ function copy_test_dir()
     if [[ -d "$1" ]]; then
 	if [[ ! -d "$2" ]]; then
 	    mkdir "$2"
+	    local warn=1
+	    local fail=1
+	else
+	    [ -f "$2/warn" ]
+	    local warn=$?
+	    [ -f "$2/fail" ]
+	    local fail=$?
 	fi
 	cp -f "$1/"* "$2/"
-	cp -f "$1.s" "$2.s"
+	if [[ -f "$1.s" ]]; then
+	    cp -f "$1.s" "$2.s"
+	fi
 	if [[ -f "$1/warn" ]]; then
-	    if [[ -f "$2/warn" ]]; then
+	    if (( warn == 0)); then
 		sed "s/$1/$2/g" < "$1/warn" > "$2/warn.tmp"
 		if diff -q "$2/warn" "$2/warn.tmp" > /dev/null; then
 		    rm -f "$2/warn.tmp"
@@ -815,16 +829,22 @@ function copy_test_dir()
 		sed "s/$1/$2/g" < "$1/warn" > "$2/warn"
 		rm -f "$2.c.html"
 	    fi
-	elif [[ -f "$2/warn" ]]; then
+	elif (( warn == 0 )); then
 	    rm -f "$2/warn" "$2.c.html"
 	fi
 	if [[ -f "$1/fail.tst" ]]; then
 	    sed "s/$1/$2/g" < "$1/fail.tst" > "$2/fail.tst"
 	    sed "s/$1/$2/g" < "$1/fail" > "$2/fail"
+	    if (( fail == 1 )); then
+		rm -f "$2.c.html"
+	    fi
 	    rm -f "$2.*tst"
 	elif [[ -f "$1.tst" ]]; then
 	    sed "s/$1/$2/g" < "$1.tst" > "$2.tst"
 	    rm -f "$2/fail.tst" "$2/fail"
+	    if (( fail == 0 )); then
+		rm -f "$2.c.html"
+	    fi
 	    if [[ "$(find $1/pid.* 2> /dev/null)" ]]; then
 		rm -f "$2/pass"
 	    fi
@@ -1040,8 +1060,10 @@ if [[ "$REQUEST_URI" == /_run/* ]] && runnable "$REQUEST_URI"; then
 		    basename="${file##*/}"
 		    basename="${basename%%.c}"
 		    cd $dirname
+		    for f in "$basename".*; do
+			cp -f "$f" "~$f"
+		    done
 		    get_edited_text > "~$basename.c"
-		    cp -f "~$basename.c" "run~$basename.c"
 		    if [[ ! -d "~$basename" && -d "$basename" ]]; then
 			copy_test_dir "$basename" "~$basename"
 		    fi
@@ -1053,7 +1075,7 @@ if [[ "$REQUEST_URI" == /_run/* ]] && runnable "$REQUEST_URI"; then
 		    rm -f "$basename.log"
 		    if ( make -f "$makefile" "$basename.s" ) > "$basename.log" 2>&1; then
 			if rm -f "$basename/fail.tst" && \
-				SANDBOX="$HTTP_SANDBOX" CFLAGS="-O2" \
+				SANDBOX="$HTTP_SANDBOX" CFLAGS="-O2 -DMTRACE=3" \
 				       make -f "$makefile" "$basename.tst" > "$basename.log"; then
 			    rm -f "$basename.log"
 			fi
@@ -1240,7 +1262,8 @@ if test -d $file; then
     tabs="$tabs<li><a href=\"${REQUEST_URI}?history\">history</a></li>"
     $PREPROC | $PANDOCT -s -V wikititle="$WIKI_TITLE"		    \
 		       -V base=$BASE_URL			    \
-		       -V pagetitle=Contents 			    \
+		       -V pagetitle="$REQUEST_URI"		    \
+		       -V notitle=true                              \
 		       -V sitenav=true				    \
 		       -V tabs="$tabs"                              \
 		       -V users="$USERS"                            \
diff --git a/src/runtest b/src/runtest
--- a/src/runtest
+++ b/src/runtest
@@ -95,19 +95,24 @@ locally()
 run_untrusted()
 {
     status=0
-    if grep -q basilisk-untrusted /etc/passwd; then
-	notrust=/tmp/$chksum
-	if ! sudo -n -u basilisk-untrusted -- \
-	     bash -c "mkdir $notrust && cp -arf * $notrust && cd $notrust && $1"; then
+    if test -n "$chksum"; then
+	if grep -q basilisk-untrusted /etc/passwd; then
+	    if ! mkdir -m 777 ../$chksum; then
+		return 1
+	    fi
+	    if ! sudo -n -u basilisk-untrusted -- \
+		 bash -c "cp -arf * ../$chksum && cd ../$chksum && $1"; then
+		status=1
+	    fi
+	    if ! cp -arf ../$chksum/* .; then
+		status=1
+	    fi
+	    sudo -n -u basilisk-untrusted -- rm -rf ../$chksum/*
+	    rm -r -f ../$chksum
+	else
+	    echo "Could not find the 'basilisk-untrusted' user" >2
 	    status=1
 	fi
-	if ! cp -arf $notrust/* .; then
-	    status=1
-	fi
-	sudo -n -u basilisk-untrusted -- rm -rf $notrust
-    else
-	echo "Could not find the 'basilisk-untrusted' user" >2
-	status=1
     fi
     return $status
 }
@@ -130,10 +135,17 @@ remotely()
     autolink=`$BASILISK/qcc -autolink -progress -source $CFLAGS $test.c`
     chksum=`(cat $test.s && pwd && echo $test) | $GENSUM | cut -d' ' -f1`.$ext
     mkdir $test/$chksum
-    mv -f _$test.c $test/$test.c
     cd $test
     cp -f $test.* $chksum 2> /dev/null || true
     rm -f $chksum/$test.c.page $chksum/$test.c.html
+    if test `echo "$test" | sed 's/^~//'` != "$test"; then
+	cd $chksum
+	for f in "$test".*; do
+	    mv -f "$f" `echo "$f" | sed 's/^~//'`
+	done
+	cd ..
+    fi
+    mv -f ../_$test.c $chksum/$test.c
     PCC="\$CC99"
     case "$CFLAGS" in
 	*-cadna*) PCC="\$CADNACC" ;;
@@ -148,7 +160,7 @@ run_untrusted()
 {
   status=0
   notrust=/tmp/$chksum
-  if ! sudo -n -u basilisk-untrusted -- bash -c "source \$HOME/.bashrc && mkdir \$notrust && cp -arf * \$notrust && cd \$notrust && \$1"; then
+  if ! sudo -n -u basilisk-untrusted -- bash -c "source \$HOME/.bashrc && mkdir \$notrust && cp -arf * \$notrust && cd \$notrust && rm -f complete && \$1 && touch complete"; then
      status=1
   fi
   if ! cp -arf \$notrust/* .; then
@@ -224,7 +236,7 @@ EOF
 	       scp -q $rhost:$chksum.tgz $chksum.tgz && \
 	       ssh $rhost rm -r -f $chksum.tgz && \
 	       tar xmzf $chksum.tgz && \
-	       rm -f $chksum.tgz $test.c $test.*ref ) > /dev/null 2>> ssh.log;
+	       rm -f $chksum.tgz $test.c $test.*ref progress complete) > /dev/null 2>> ssh.log;
     then
 	cat ssh.log >> fail
     fi
