Default Makefile improvements for web generation
Ignore-this: f7194fe2acf9213bfbe9f4175010653a

darcs-hash:6c18b3812ab414a8a8c404b712ddd7eae16b1f29

diff --git a/src/Makefile.defs b/src/Makefile.defs
--- a/src/Makefile.defs
+++ b/src/Makefile.defs
@@ -68,15 +68,30 @@ clean:
 %.plot: %.plot.page
 	ln -s -f $< $@
 
-%.3D.s: %.3D.c $(QCC) Makefile
-	@echo qcc -autolink $(CFLAGS) -grid=octree -o $*/$* $*.c $(LIBS) -lm
-	@rm -f $*/warn
-	@OPENGLIBS="$(OPENGLIBS)" $(QCC) -autolink -nolineno $(STRIPFLAGS) $(subst -g ,,$(subst -O2 ,,$(CFLAGS) -grid=octree)) $< -o $@ $(LIBS) -lm
+define compile_failed =
+(mkdir -p $* && 										\
+	echo "qcc -autolink $(CFLAGS) -o $*/$* $*.c $(LIBS) -lm" > $*/fail &&			\
+	cat $*.log~ >> $*/fail &&								\
+	echo "make: *** [$*.s] Error 1" >> $*/fail &&						\
+	rm -f $*.*tst &&									\
+	$(GENSUM) $*.c > $*/fail.tst &&								\
+	cat $*/fail 2> /dev/stderr &&								\
+	exit 1)
+endef
 
-%.s: %.c $(QCC) Makefile
+%.3D.s: %.3D.c $(QCC)
+	@echo qcc -autolink $(CFLAGS) -grid=octree -o $*/$* $*.c $(LIBS) -lm
+	@rm -f $*/fail
+	@OPENGLIBS="$(OPENGLIBS)" $(QCC) -autolink -nolineno $(STRIPFLAGS) $(subst -g ,,$(subst -O2 ,,$(CFLAGS) -grid=octree)) $< -o $@ $(LIBS) -lm 2> $*.log~ || $(compile_failed)
+	@chmod -x $@
+	@rm -f $*.log~ $*/fail
+
+%.s: %.c $(QCC)
 	@echo qcc -autolink $(CFLAGS) -o $*/$* $*.c $(LIBS) -lm
-	@rm -f $*/warn
-	@OPENGLIBS="$(OPENGLIBS)" $(QCC) -autolink -nolineno $(STRIPFLAGS) $(subst -g ,,$(subst -O2 ,,$(CFLAGS))) $< -o $@ $(LIBS) -lm
+	@rm -f $*/fail
+	@OPENGLIBS="$(OPENGLIBS)" $(QCC) -autolink -nolineno $(STRIPFLAGS) $(subst -g ,,$(subst -O2 ,,$(CFLAGS))) $< -o $@ $(LIBS) -lm 2> $*.log~ ||  $(compile_failed)
+	@chmod -x $@
+	@rm -f $*.log~ $*/fail
 
 %.prof: %.c
 	$(QCC) -autolink $(subst -DTRASH=1,,$(CFLAGS)) -g -no-pie -pg $< -o $*/$* -lm
@@ -89,9 +104,11 @@ clean:
 %.dot.png: %.dot
 	dot -Tpng -o $@ < $<
 
+# fixme: this is obsolete
 %/plot.png: %.plot
 	cd $* && gnuplot -e "batch=1; PNG=\"$(PNG)\"; set term $(PNG) enhanced font \",10\"; set output 'plot.png'; set macros;" ../$< || rm -f plot.png
 
+# warning: if this recipe is changed, runtest needs to be updated
 %/plots: %.c $(BASILISK)/gnuplot.awk $(BASILISK)/python.awk \
 		$(BASILISK)/gnuplot.sh
 	cd $* && awk -f $(BASILISK)/gnuplot.awk < ../$*.c > plots && \
@@ -111,15 +128,13 @@ clean:
 
 %.tags: %.page $(QCC)
 	$(QCC) -tags $<
-	ln -s -f $< $*
-	( ! test -d $(BASILISK_WIKI)/cache ) || \
-	rm -f $(subst $(BASILISK_WIKI),$(BASILISK_WIKI)/cache,$(PWD))/$<
+
+%.tags: % $(QCC)
+	$(QCC) -tags $<
 
 %.itags: %.tags $(subst .page,.tags,$(ALLPAGES)) $(BASILISK)/includedin.sh
 	sh $(BASILISK)/includedin.sh $* > $@
 	rm -f $*.html
-	( ! test -d $(BASILISK_WIKI)/cache ) || \
-	rm -f $(subst $(BASILISK_WIKI),$(BASILISK_WIKI)/cache,$(PWD))/$(subst .tags,.page,$<)
 
 # lists external symbols of executables
 extern = nm -u $(1) | sed -n 's/^[ ]*U \(.*\)/\1/p' | sort | uniq
@@ -146,10 +161,26 @@ whitelist: $(subst .c,.exe,$(filter-out $(EXCLUDE),$(ALLTESTS))) \
 	$(CC) -shared $*.o $*_wrap.o -o _$*.so
 
 # HTML
-%.html: %.page %.tags $(BASILISK)/Makefile.defs 	\
-		$(BASILISK)/templates/page.static 	\
-		$(BASILISK)/plugins/literate-c		\
-		$(BASILISK)/plugins/codeblock		\
+%.html: %.page %.tags $(BASILISK)/Makefile.defs 	  \
+		$(BASILISK)/darcsit/templates/page.static \
+		$(BASILISK)/darcsit/literate-c		  \
+		$(BASILISK)/darcsit/codeblock		  \
+		$(BASILISK)/page2html
+	$(BASILISK)/page2html $< > $@
+	@test -s $@ || exit 1
+
+%.c.html: %.c %.c.tags $(BASILISK)/Makefile.defs 	   \
+		$(BASILISK)/darcsit/templates/page.static  \
+		$(BASILISK)/darcsit/literate-c		   \
+		$(BASILISK)/darcsit/codeblock		   \
+		$(BASILISK)/page2html
+	$(BASILISK)/page2html $< > $@
+	@test -s $@ || exit 1
+
+%.h.html: %.h %.h.tags $(BASILISK)/Makefile.defs 	   \
+		$(BASILISK)/darcsit/templates/page.static  \
+		$(BASILISK)/darcsit/literate-c		   \
+		$(BASILISK)/darcsit/codeblock		   \
 		$(BASILISK)/page2html
 	$(BASILISK)/page2html $< > $@
 	@test -s $@ || exit 1
@@ -163,7 +194,7 @@ LINKCHECKER = linkchecker --no-warnings --no-status --anchors	\
 	$(LINKCHECKER) -r 1 $<
 
 # generated makefiles
-Makefile.tests: Makefile $(BASILISK)/tests.sh
+Makefile.tests: $(BASILISK)/tests.sh
 	sh $(BASILISK)/tests.sh
 
 %.s.d: %.c $(QCC)
