Improved ppm2... scripts
Ignore-this: 7b4184f33abf6705eeccc25950da92c0

darcs-hash:b222bdc4cf7f720aa3aa6c95238b06f76c1b0654

diff --git a/src/ppm2gif b/src/ppm2gif
--- a/src/ppm2gif
+++ b/src/ppm2gif
@@ -4,9 +4,8 @@ CONVERT="`which convert`"
 GIFSICLE="`which gifsicle`"
 
 if test -z "$CONVERT" -o -z "$GIFSICLE"; then
-    echo "ppm2gif: warning: could not find 'convert' or 'gifsicle'" > /dev/stderr
-    echo "ppm2gif: the output will just be concatenated PPM files" \
-	 > /dev/stderr
+    echo "ppm2gif: warning: could not find 'convert' or 'gifsicle'" >&2
+    echo "ppm2gif: the output will just be concatenated PPM files" >&2
     cat
 else
     command="gifsicle --colors 256 --optimize --delay 5"
@@ -31,7 +30,7 @@ else
     $ppm ppm:- $log-%04d.gif
     if $command $log-*.gif 2> $log; then :
     else
-	cat $log > /dev/stderr
+	cat $log >&2
 	rm -f $log*
 	exit 1
     fi
diff --git a/src/ppm2mp4 b/src/ppm2mp4
--- a/src/ppm2mp4
+++ b/src/ppm2mp4
@@ -6,45 +6,35 @@ if test -z "$AVCONV"; then
 fi
 
 if test -z "$AVCONV"; then
-    echo "ppm2mp4: warning: could not find 'avconv' or 'ffmpeg'" > /dev/stderr
-    echo "ppm2mp4: the output will just be concatenated PPM files" \
-	> /dev/stderr
+    echo "ppm2mp4: warning: could not find 'avconv' or 'ffmpeg'" >&2
+    echo "ppm2mp4: the output will just be concatenated PPM files" >&2
     command=cat
-    log=/dev/null
 else
     # -crf 18 low compression/high quality, 28 high compression/low quality
     # see https://trac.ffmpeg.org/wiki/Encode/H.264
     # -r 15  '15 frames/sec'
-    if test -d "$TMPDIR" ; then
-	log=`mktemp $TMPDIR/ppm2mp4.XXXXXX`
-	out=`mktemp $TMPDIR/ppm2mp4.XXXXXX`
-    else
-	log=`mktemp /tmp/ppm2mp4.XXXXXX`
-	out=`mktemp /tmp/ppm2mp4.XXXXXX`
-    fi
     while test $# -gt 0; do
 	case $1 in
 	    -r) shift; rate="-r $1" ;;
+	    *) options="$options $1" ;;
 	esac
 	shift
     done
-    command="$AVCONV -f image2pipe -vcodec ppm $rate -i - -c:v libx264 -preset slow -crf 18 -vf format=yuv420p -y -f mp4"
-    while test $# -gt 0; do
-	case $1 in
-	    -r) shift ;;
-	    *) command="$command $1" ;;
-	esac
-	shift
-    done
+    command="$AVCONV -f image2pipe -vcodec ppm $rate -i - -c:v libx264 -preset slow -tune zerolatency -crf 18 -vf format=yuv420p -y -f mpegts $options -"
 fi
 
-if $command $out 2> $log; then :
+if test -d "$TMPDIR" ; then
+    log=`mktemp $TMPDIR/ppm2mp4.XXXXXX`
 else
-    cat $log > /dev/stderr
-    rm -f $log $out
+    log=`mktemp /tmp/ppm2mp4.XXXXXX`
+fi
+
+if $command 2> $log; then :
+else
+    cat $log >&2
+    rm -f $log
     exit 1
 fi
-cat $out
-rm -f $log $out
+rm -f $log
 
 exit 0
diff --git a/src/ppm2mpeg b/src/ppm2mpeg
--- a/src/ppm2mpeg
+++ b/src/ppm2mpeg
@@ -6,27 +6,26 @@ if test -z "$AVCONV"; then
 fi
 
 if test -z "$AVCONV"; then
-    echo "ppm2mpeg: warning: could not find 'avconv' or 'ffmpeg'" > /dev/stderr
-    echo "ppm2mpeg: the output will just be concatenated PPM files" \
-	> /dev/stderr
+    echo "ppm2mpeg: warning: could not find 'avconv' or 'ffmpeg'" >&2
+    echo "ppm2mpeg: the output will just be concatenated PPM files" >&2
     command=cat
-    log=/dev/null
 else
     command="$AVCONV -f image2pipe -vcodec ppm -i - -vcodec mpeg1video -b 1800K -f mpeg1video"
     while test $# -gt 0; do
 	command="$command $1"
 	shift
     done
-    if test -d "$TMPDIR" ; then
-	log=`mktemp $TMPDIR/ppm2mpeg.XXXXXX`
-    else
-	log=`mktemp /tmp/ppm2mpeg.XXXXXX`
-    fi
+fi
+
+if test -d "$TMPDIR" ; then
+    log=`mktemp $TMPDIR/ppm2mpeg.XXXXXX`
+else
+    log=`mktemp /tmp/ppm2mpeg.XXXXXX`
 fi
 
 if $command - 2> $log; then :
 else
-    cat $log > /dev/stderr
+    cat $log >&2
     rm -f $log
     exit 1
 fi
diff --git a/src/ppm2ogv b/src/ppm2ogv
--- a/src/ppm2ogv
+++ b/src/ppm2ogv
@@ -6,20 +6,11 @@ if test -z "$AVCONV"; then
 fi
 
 if test -z "$AVCONV"; then
-    echo "ppm2ogv: warning: could not find 'avconv' or 'ffmpeg'" > /dev/stderr
-    echo "ppm2ogv: the output will just be concatenated PPM files" \
-	> /dev/stderr
+    echo "ppm2ogv: warning: could not find 'avconv' or 'ffmpeg'" >&2
+    echo "ppm2ogv: the output will just be concatenated PPM files" >&2
     command=cat
-    log=/dev/null
 else
     # -r 15  '15 frames/sec'
-    if test -d "$TMPDIR" ; then
-	log=`mktemp $TMPDIR/ppm2ogv.XXXXXX`
-	out=`mktemp $TMPDIR/ppm2ogv.XXXXXX`
-    else
-	log=`mktemp /tmp/ppm2ogv.XXXXXX`
-	out=`mktemp /tmp/ppm2ogv.XXXXXX`
-    fi
     while test $# -gt 0; do
 	case $1 in
 	    -r) shift; rate="-r $1" ;;
@@ -36,9 +27,17 @@ else
     done
 fi
 
+if test -d "$TMPDIR" ; then
+    log=`mktemp $TMPDIR/ppm2ogv.XXXXXX`
+    out=`mktemp $TMPDIR/ppm2ogv.XXXXXX`
+else
+    log=`mktemp /tmp/ppm2ogv.XXXXXX`
+    out=`mktemp /tmp/ppm2ogv.XXXXXX`
+fi
+
 if $command $out 2> $log; then :
 else
-    cat $log > /dev/stderr
+    cat $log >&2
     rm -f $log $out
     exit 1
 fi
